# Generated by Django 2.0 on 2021-05-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='abc@gmailcom', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.IntegerField(default=459),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
