# Generated by Django 2.0 on 2021-05-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210510_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='hostname@gmail.com', max_length=254, unique=True),
        ),
    ]
