# Generated by Django 2.0 on 2021-05-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210510_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='hostname@gmail.com', max_length=254),
        ),
    ]
