# Generated by Django 2.0 on 2021-05-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='hostmail@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=459),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
