# Generated by Django 2.0 on 2021-05-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='otp',
            new_name='employeeid',
        ),
    ]
